name: mask2former-adverse
channels:
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.9.9
  - cuda-nvrtc=11.8.89
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=24.2
  - pthread-stubs=0.3
  - python=3.8.20
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==0.25.0
      - addict==2.4.0
      - albumentations==1.3.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.1.8
      - cmake==3.25.0
      - colorama==0.4.6
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.1
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.14.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lit==15.0.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.3
      - mdurl==0.1.2
      - mmcv-full==1.7.2
      - mmdet==2.28.2
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.1
      - ninja==1.13.0
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==9.5.0
      - platformdirs==4.3.6
      - psutil==7.1.0
      - pycocotools==2.0.7
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - qudida==0.0.4
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - setuptools==60.2.0
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.9.8
      - tokenizers==0.15.2
      - tomli==2.2.1
      - torch==2.0.0+cu118
      - torchaudio==2.0.1+cu118
      - torchvision==0.15.1+cu118
      - tornado==6.4.2
      - tqdm==4.65.2
      - transformers==4.37.2
      - triton==2.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - visdom==0.2.4
      - websocket-client==1.8.0
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.20.2
